export const routesOrder = [
  "/",
  "/about",
  "/work",
  "/work/1",
  "/work/1/design",
  "/work/1/learning",
  "/work/2",
  "/work/2/design",
  "/work/2/learning",
  "/work/3",
  "/work/3/design",
  "/work/3/learning",
  "/work/4",
  "/work/4/design",
  "/work/4/learning",
  "/contact",
];

export const routes = {
  home: "/",
  about: "/about",
  work: "/work",
  work1: "/work/1",
  work1Design: "/work/1/design",
  work1Learning: "/work/1/learning",
  work2: "/work/2",
  work2Design: "/work/2/design",
  work2Learning: "/work/2/learning",
  work3: "/work/3",
  work3Design: "/work/3/design",
  work3Learning: "/work/3/learning",
  work4: "/work/4",
  work4Design: "/work/4/design",
  work4Learning: "/work/4/learning",
  contact: "/contact",
};
